Append userSession check logic
Uni-class/catch-up-repo pull request #339
Opened 2024-08-20 04:57 UTC by 1000chw

## 📍 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정

## ❗️ 관련 이슈 [#]
close #338 

## 📄 개요
- join을 할 때 이미 join한 세션인지 확인하지 않고 디비에 넣음
- 확인 한번 거친 후 join하도록 추가

## 🔁 변경 사항
### 변경 내용을 적어주세요 (커밋 번호를 적어주세요)
- 왜, 어떻게 변경했는지 상세한 설명을 작성 (생략 가능)

## 📸 동작 화면 스크린샷

## 👀 기타 논의 사항

2024-08-20 11:45 UTC, nayounsang commented on packages/api-server/src/users/users.service.ts
> +    });
그럼 참가자가 /join 두번쨰로 요청을 보내면 에러가 뜨는거 아니야?
굳이 에러를 뱉어내야하나 고민
그대로 userSession 뱉으면 될거같아서

2024-08-21 07:23 UTC, easyandones requested changes

2024-08-21 07:23 UTC, easyandones commented on packages/api-server/src/users/users.service.ts
> +    });
나도 그 방향이 좋다고 봄.
사용자가 직접 url 접속이나 다른걸로 재요청을 넣을 수도 있고 아님 아직 동기화되지 않은 다른 브라우저나 탭에서 요청이 수행될 수도 있음
네트워크 자체 오류로 2번 요청이 갈 수도 있음

다양한 조건이 있을 것 같아서 굳이 저기서 오류를 내기보다는 이미 존재하면 존재하는 객체를 반환하는게 더 좋을듯

2024-08-21 07:24 UTC, easyandones requested changes

2024-08-21 07:24 UTC, easyandones commented on packages/api-server/src/users/users.service.ts
> +    }
나도 그 방향이 좋다고 봄.
사용자가 직접 url 접속이나 다른걸로 재요청을 넣을 수도 있고 아님 아직 동기화되지 않은 다른 브라우저나 탭에서 요청이 수행될 수도 있음
네트워크 자체 오류로 2번 요청이 갈 수도 있음

다양한 조건이 있을 것 같아서 굳이 저기서 오류를 내기보다는 이미 존재하면 존재하는 객체를 반환하는게 더 좋을듯

2024-08-21 08:55 UTC, 1000chw commented on packages/api-server/src/users/users.service.ts
> +    }
그런가..?  ㅇㅋㅇㅋ

2024-08-21 11:31 UTC, easyandones approved these changes

2024-08-21 11:32 UTC, merged