feat: Create Button Component
Uni-class/catch-up-repo pull request #90
Opened 2024-07-18 09:08 UTC by easyandones

## 📍 PR 타입 (하나 이상 선택)
 - [기능 추가]

## ❗️ 관련 이슈 [#]
#89 

## 📄 개요
- 버튼 컴포넌트 생성

## 🔁 변경 사항
- 임시 버튼 컴포넌트

## 📸 동작 화면 스크린샷
<img width="329" alt="image" src="https://github.com/user-attachments/assets/ab1363d8-b833-4498-81a4-ffc79ada4ad5">
<img width="318" alt="image" src="https://github.com/user-attachments/assets/7994d837-2b66-455a-864e-0719b275574f">

- 캡처 화면에 나오진 않지만 hover active 등의 이벤트가 처리됨

2024-07-18 16:24 UTC, nayounsang requested changes
ui개발시 storybook을 활용하면 커뮤니케이션 비용을 줄일 수 있음(스토리북 작성은 나에게 문의)

2024-07-18 16:24 UTC, nayounsang commented on packages/front-end/components/Button.tsx
> +
styled 이용추천! 왜냐하면 버튼의 로직은 그대로두고 스타일만 손댈때 쓰는거임
그럼 Props설정을 굳이할 필요가 없음(정확힌 스타일에 관한 vairant만 설정해주면 됨)
왜냐하면 button tag에 기본적으로 주어지는 attribute를 이대로면 활용 못함(이외에도 react에 기본적으로 주어지는 ref props가 있음, 현재는 활용못함)
만약, css 외 특정로직을 기본적으로 수행하는 버튼의 경우엔 extend와 spread를 이용한 props 관리 가능
```
interface PropType extends ButtonHTMLAttributes<HTMLButtonElement> {
  // ... my additional props
  children: ReactNode 
}

export const Button({children, props1,props2,...attr}){
// ...process additional props 
return <button {...attr}>{children}</button>
}
```
위같은 로직도 추후 종종쓰일 것으로 보이나,
지금 경우에는 styled를 사용하는것이 옳음
그리고 내부는 text가 아닌 ReactNode type의 children으로 주는게 맞다고 생각

2024-07-22 04:44 UTC, easyandones commented on packages/front-end/components/Button.tsx
> +
반영 완료
확인 바랍니다

2024-07-22 05:39 UTC, nayounsang approved these changes

2024-07-22 05:39 UTC, merged